name: Testing API
on: [push, pull_request]
jobs:
  testing-api:
    runs-on: ubuntu-latest
    env:
      SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Create and activate virtualenv
        run: |
          pip3 install virtualenv
          virtualenv venv
          source venv/bin/activate
      - name: Initialize dependencies
        run: |
          pip install dvc-gs
          pip install -r testing/requirements.txt
      - name: Pull data from DVC
        run: dvc pull
      
      - name: Run the pipeline with DVC
        run: dvc repro

      - name: Push the outcomes to DVC remote storage 
        run: dvc push
